language: node_js
node_js:
    - "8"
services:
    - docker
script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
    - docker build . -t swarmpit/ethstats
    - docker push swarmpit/ethstats
